# GitHub action to run linting

name: run-linting

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.18"
          cache: "pip"
      
      - name: Restore pip packages cache
        uses: actions/cache@v4
        id: pip-cache
        with:
          path: /opt/hostedtoolcache/Python/3.8.18/x64/site-packages
          key: lint-packages-${{ hashFiles('pyproject.toml') }}
          restore-keys: lint-packages-

      - name: Install dependencies
        if: steps.pip-cache.outputs.cache-hit != 'true'
        run: make install

      - name: Lint
        id: lint
        run: |
          make lint-check
      
